"""add person.ndca_pro_am_status

Revision ID: 02a9bfc25eda
Revises: 0fbf15dcd790
Create Date: 2026-08-08 09:26:49.284219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a9bfc25eda'
down_revision: Union[str, Sequence[str], None] = '0fbf15dcd790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('ndca_pro_am_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'ndca_pro_am_status')
    # ### end Alembic commands ###
