"""initial schema

Revision ID: 80e2a85f0d60
Revises: 
Create Date: 2026-08-02 10:46:29.672147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e2a85f0d60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('sanctioning_body', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_code')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pairwise_outcome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comp_event_id', sa.Integer(), nullable=True),
    sa.Column('winner_entry_id', sa.Integer(), nullable=True),
    sa.Column('loser_entry_id', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('given_name', sa.String(), nullable=True),
    sa.Column('family_name', sa.String(), nullable=True),
    sa.Column('wdsf_min', sa.String(), nullable=True),
    sa.Column('ndca_number', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('is_adjudicator', sa.Boolean(), nullable=False),
    sa.Column('is_professional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ndca_number'),
    sa.UniqueConstraint('wdsf_min')
    )
    op.create_table('rating',
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('mu', sa.Numeric(), nullable=True),
    sa.Column('sigma', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('subject_type', 'subject_id', 'style', 'as_of', 'method')
    )
    op.create_table('raw_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_sha256', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('parser_version', sa.String(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'url', 'content_sha256')
    )
    op.create_table('affiliation',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'organization_id')
    )
    op.create_table('comp_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('raw_title', sa.String(), nullable=False),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('proficiency', sa.String(), nullable=True),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.Column('role_class', sa.String(), nullable=True),
    sa.Column('dances', sa.JSON(), nullable=True),
    sa.Column('is_scholarship', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'raw_title')
    )
    op.create_table('organization_alias',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'raw_name')
    )
    op.create_table('partnership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=True),
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['leader_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('leader_id', 'follower_id', 'kind')
    )
    op.create_table('person_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('raw_name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_name', 'source', 'person_id')
    )
    op.create_table('resolution_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('candidate_person_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('partnership_id', sa.Integer(), nullable=True),
    sa.Column('competitor_no', sa.String(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['partnership_id'], ['partnership.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comp_event_id', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.String(), nullable=False),
    sa.Column('round_order', sa.Integer(), nullable=False),
    sa.Column('entries_in', sa.Integer(), nullable=True),
    sa.Column('recalled_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comp_event_id'], ['comp_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('judge_person_id', sa.Integer(), nullable=True),
    sa.Column('dance', sa.String(), nullable=True),
    sa.Column('recalled', sa.Boolean(), nullable=True),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.ForeignKeyConstraint(['judge_person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'entry_id', 'judge_person_id', 'dance')
    )
    op.create_table('result',
    sa.Column('comp_event_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('placement_low', sa.Integer(), nullable=True),
    sa.Column('placement_high', sa.Integer(), nullable=True),
    sa.Column('made_final', sa.Boolean(), nullable=True),
    sa.Column('field_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comp_event_id'], ['comp_event.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ),
    sa.PrimaryKeyConstraint('comp_event_id', 'entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('mark')
    op.drop_table('round')
    op.drop_table('entry')
    op.drop_table('resolution_queue')
    op.drop_table('person_alias')
    op.drop_table('partnership')
    op.drop_table('organization_alias')
    op.drop_table('comp_event')
    op.drop_table('affiliation')
    op.drop_table('raw_document')
    op.drop_table('rating')
    op.drop_table('person')
    op.drop_table('pairwise_outcome')
    op.drop_table('organization')
    op.drop_table('competition')
    # ### end Alembic commands ###
