"""add competition.source_updated_at

Revision ID: 946bf44111c1
Revises: 80e2a85f0d60
Create Date: 2026-08-04 14:42:19.522257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946bf44111c1'
down_revision: Union[str, Sequence[str], None] = '80e2a85f0d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competition', 'source_updated_at')
    # ### end Alembic commands ###
