"""add scheduled_heat table

Revision ID: a0799bd18964
Revises: 02a9bfc25eda
Create Date: 2026-09-01 15:53:01.241826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0799bd18964'
down_revision: Union[str, Sequence[str], None] = '02a9bfc25eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_heat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('partnership_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('round_name', sa.String(), nullable=False),
    sa.Column('heat_number', sa.String(), nullable=True),
    sa.Column('session', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('competitor_no', sa.String(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['partnership_id'], ['partnership.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_event_id', 'round_name', 'partnership_id')
    )
    op.create_index(op.f('ix_scheduled_heat_competition_id'), 'scheduled_heat', ['competition_id'], unique=False)
    op.create_index(op.f('ix_scheduled_heat_partnership_id'), 'scheduled_heat', ['partnership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_heat_partnership_id'), table_name='scheduled_heat')
    op.drop_index(op.f('ix_scheduled_heat_competition_id'), table_name='scheduled_heat')
    op.drop_table('scheduled_heat')
    # ### end Alembic commands ###
